title: Orka Blog
author: alexamart
email: alexamart@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Orka Ink's Blog
theme: minima
# social links
twitter_username: dalxmart # DO NOT include the @ character, or else the build will fail!
github_username:  alexamart # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
